/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.equivalencia.gui;

import com.equivalencia.modelo.CadeiaConjuntoFinito;
import com.equivalencia.modelo.InstrucaoMonolitica;
import com.equivalencia.modelo.InstrucaoRotuladaComposta;
import com.equivalencia.modelo.ParesDeRotulos;
import com.equivalencia.modelo.VerificaEquivalencia;
import com.equivalencia.utilitarios.Utilitario;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URL;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import jdk.nashorn.internal.runtime.ScriptRuntime;
import org.apache.commons.io.FileUtils;

/**
 *
 * @author clarel
 */
public class Tela extends javax.swing.JFrame {

	/**
	 * Creates new form Tela
	 */
	public Tela() {
		this.setTitle("Equivalência Forte de Programas - Clarel de Menezes Spies Filho");
		initComponents();
		this.setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		entradas2 = new javax.swing.JTextPane();
		jScrollPane2 = new javax.swing.JScrollPane();
		entradas1 = new javax.swing.JTextPane();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jScrollPane4 = new javax.swing.JScrollPane();
		rotuladas2 = new javax.swing.JTextPane();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jScrollPane5 = new javax.swing.JScrollPane();
		conjuntos2 = new javax.swing.JTextPane();
		jLabel6 = new javax.swing.JLabel();
		jScrollPane7 = new javax.swing.JScrollPane();
		simplificadas2 = new javax.swing.JTextPane();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jScrollPane10 = new javax.swing.JScrollPane();
		resultado = new javax.swing.JTextPane();
		jScrollPane8 = new javax.swing.JScrollPane();
		conjuntos1 = new javax.swing.JTextPane();
		jScrollPane9 = new javax.swing.JScrollPane();
		simplificadas1 = new javax.swing.JTextPane();
		jScrollPane6 = new javax.swing.JScrollPane();
		rotuladas1 = new javax.swing.JTextPane();
		arquivo1 = new javax.swing.JButton();
		arquivo2 = new javax.swing.JButton();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		setLocation(new java.awt.Point(0, 0));
		setPreferredSize(new java.awt.Dimension(1366, 768));
		setResizable(false);

		jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

		jScrollPane1.setViewportView(entradas2);

		jScrollPane2.setViewportView(entradas1);

		jLabel1.setText("Programa 1 - Monolítico");

		jLabel2.setText("Programa 2 - Monolítico");

		jButton2.setText("Iniciar");
		jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton2MouseClicked(evt);
			}
		});

		rotuladas2.setEditable(false);
		jScrollPane4.setViewportView(rotuladas2);

		jLabel3.setText("Programa 1");

		jLabel4.setText("Programa 2");

		jLabel5.setText("1 - Instruções Rotuladas Compostas");

		conjuntos2.setEditable(false);
		jScrollPane5.setViewportView(conjuntos2);

		jLabel6.setText("2 - Cadeia de Conjuntos Finitos");

		simplificadas2.setEditable(false);
		jScrollPane7.setViewportView(simplificadas2);

		jLabel7.setText("3 - Simplificação (se necessário)");

		jLabel8.setText("4 - Resultado da Verificação de Equivalência");

		resultado.setEditable(false);
		jScrollPane10.setViewportView(resultado);

		conjuntos1.setEditable(false);
		jScrollPane8.setViewportView(conjuntos1);

		simplificadas1.setEditable(false);
		jScrollPane9.setViewportView(simplificadas1);

		rotuladas1.setEditable(false);
		jScrollPane6.setViewportView(rotuladas1);

		arquivo1.setText("Arquivo");
		arquivo1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				arquivo1MouseClicked(evt);
			}
		});

		arquivo2.setText("Arquivo");
		arquivo2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				arquivo2MouseClicked(evt);
			}
		});

		jButton1.setText("Ajuda");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton1MouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel2).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(arquivo2))
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(arquivo1))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup().addComponent(jButton1).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(jButton2))
								.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(0,
										0, Short.MAX_VALUE)))
						.addGap(106, 106, 106)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane8).addComponent(jScrollPane9).addComponent(jLabel3).addComponent(jLabel6).addComponent(jLabel7).addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false).addComponent(jLabel4).addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE).addComponent(jScrollPane4).addComponent(jScrollPane7)).addGap(43, 43, 43))
								.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel5).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel8)).addGap(256, 256, 256)));
		jPanel1Layout
				.setVerticalGroup(
						jPanel1Layout
								.createParallelGroup(
										javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(
										jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jLabel3).addComponent(jLabel4).addComponent(arquivo1))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(arquivo2)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jScrollPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton2).addComponent(jButton1)))
														.addGroup(jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel5).addComponent(jLabel8)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(jPanel1Layout.createSequentialGroup()
																				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGap(19, 19, 19).addComponent(jLabel6))
																		.addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)).addGap(18, 18, 18)
																.addComponent(jLabel7).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
												.addContainerGap(48, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0, 0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0, 49, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton2MouseClicked
		this.rotuladas1.setText("");
		this.rotuladas2.setText("");
		this.conjuntos1.setText("");
		this.conjuntos2.setText("");
		this.simplificadas1.setText("");
		this.simplificadas2.setText("");
		this.resultado.setText("");

		try {
			List<InstrucaoMonolitica> instrucoesMonoliticas1 = InstrucaoMonolitica.criaListaInstrucoesMonoliticasParaPrograma(Utilitario.textoParaListaString(this.entradas1.getText()));
			List<InstrucaoMonolitica> instrucoesMonoliticas2 = InstrucaoMonolitica.criaListaInstrucoesMonoliticasParaPrograma(Utilitario.textoParaListaString(this.entradas2.getText()));
			VerificaEquivalencia equivalencia = new VerificaEquivalencia(instrucoesMonoliticas1, instrucoesMonoliticas2);

			for (InstrucaoRotuladaComposta intrucao : equivalencia.getInstrucoesCompostas1()) {
				this.rotuladas1.setText(this.rotuladas1.getText() + "\n" + intrucao.toStringComRotulo());
			}

			for (InstrucaoRotuladaComposta intrucao : equivalencia.getInstrucoesCompostas2()) {
				this.rotuladas2.setText(this.rotuladas2.getText() + "\n" + intrucao.toStringComRotulo());
			}

			for (CadeiaConjuntoFinito conjunto : equivalencia.getCadeiaConjuntosFinitos1()) {
				this.conjuntos1.setText(this.conjuntos1.getText() + "\n" + conjunto.toString());
			}

			for (CadeiaConjuntoFinito conjunto : equivalencia.getCadeiaConjuntosFinitos2()) {
				this.conjuntos2.setText(this.conjuntos2.getText() + "\n" + conjunto.toString());
			}

			if (equivalencia.isHouveSimplificacao()) {
				for (InstrucaoRotuladaComposta intrucao : equivalencia.getInstrucoesCompostasSimplificadas1()) {
					this.simplificadas1.setText(this.simplificadas1.getText() + "\n" + intrucao.toStringComRotulo());
				}

				for (InstrucaoRotuladaComposta intrucao : equivalencia.getInstrucoesCompostasSimplificadas2()) {
					this.simplificadas2.setText(this.simplificadas2.getText() + "\n" + intrucao.toStringComRotulo());
				}
			}
			
		

			this.resultado.setText(equivalencia.getResultado().getMensagem()+"\n");
			
			for(ParesDeRotulos par:equivalencia.getParesDeRotulos()){
				this.resultado.setText(this.resultado.getText()+"\n"+par.toString());
			}

		} catch (Exception ex) {
			resultado.setText("Entradas monolíticas em formato inválido!");
		}

	}// GEN-LAST:event_jButton2MouseClicked

	private void arquivo1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_arquivo1MouseClicked
		try {

			final JFileChooser fc = new JFileChooser(System.getProperty("user.dir"));
			FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos de texto", "txt");
			fc.setFileFilter(filter);

			int response = fc.showOpenDialog(fc);

			if (response == JFileChooser.APPROVE_OPTION) {

				this.entradas1.setText(FileUtils.readFileToString(fc.getSelectedFile()));
			}

		} catch (Exception ex) {

		}
	}// GEN-LAST:event_arquivo1MouseClicked

	private void arquivo2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_arquivo2MouseClicked
		try {
			final JFileChooser fc = new JFileChooser(System.getProperty("user.dir"));
			FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivos de texto", "txt");
			fc.setFileFilter(filter);

			int response = fc.showOpenDialog(fc);

			if (response == JFileChooser.APPROVE_OPTION) {

				this.entradas2.setText(FileUtils.readFileToString(fc.getSelectedFile()));
			}
		} catch (IOException ex) {

		}
	}// GEN-LAST:event_arquivo2MouseClicked

	private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButton1MouseClicked
		try {
			Desktop.getDesktop().browse(new URL("https://github.com/clarel/EquivalenciaDeProgramas").toURI());
		} catch (Exception ex) {

		}
	}// GEN-LAST:event_jButton1MouseClicked

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel. For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Tela().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton arquivo1;
	private javax.swing.JButton arquivo2;
	private javax.swing.JTextPane conjuntos1;
	private javax.swing.JTextPane conjuntos2;
	private javax.swing.JTextPane entradas1;
	private javax.swing.JTextPane entradas2;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane10;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JScrollPane jScrollPane6;
	private javax.swing.JScrollPane jScrollPane7;
	private javax.swing.JScrollPane jScrollPane8;
	private javax.swing.JScrollPane jScrollPane9;
	private javax.swing.JTextPane resultado;
	private javax.swing.JTextPane rotuladas1;
	private javax.swing.JTextPane rotuladas2;
	private javax.swing.JTextPane simplificadas1;
	private javax.swing.JTextPane simplificadas2;
	// End of variables declaration//GEN-END:variables
}
